In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('owid-covid-data.csv')
data

,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_100k
0,ABW,Aruba,2020-03-13,2,2,0,0,18.733,18.733,0.0,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
1,ABW,Aruba,2020-03-20,4,2,0,0,37.465,18.733,0.0,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
2,ABW,Aruba,2020-03-24,12,8,0,0,112.395,74.930,0.0,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
3,ABW,Aruba,2020-03-25,17,5,0,0,159.227,46.831,0.0,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
4,ABW,Aruba,2020-03-26,19,2,0,0,177.959,18.733,0.0,...,13.085,7.452,35973.781,NaN,NaN,11.62,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19491,NaN,International,2020-02-28,705,0,4,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19492,NaN,International,2020-02-29,705,0,6,2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19493,NaN,International,2020-03-01,705,0,6,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19494,NaN,International,2020-03-02,705,0,6,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19495,NaN,International,2020-03-10,696,-9,7,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data_p = data.pivot(index='location',columns='date',values='total_cases')

In [7]:
data_p.to_csv('world_pivot.csv')

In [8]:
country = pd.read_csv('country.csv')
country

        Country Name   region                                   Image URL
0             Angola   Africa  https://www.countryflags.io/ao/flat/64.png
1            Burundi   Africa  https://www.countryflags.io/bi/flat/64.png
2              Benin   Africa  https://www.countryflags.io/bj/flat/64.png
3       Burkina Faso   Africa  https://www.countryflags.io/bf/flat/64.png
4           Botswana   Africa  https://www.countryflags.io/bw/flat/64.png
..               ...      ...                                         ...
210  Solomon Islands  Oceania  https://www.countryflags.io/sb/flat/64.png
211            Tonga  Oceania  https://www.countryflags.io/to/flat/64.png
212           Tuvalu  Oceania  https://www.countryflags.io/tv/flat/64.png
213          Vanuatu  Oceania  https://www.countryflags.io/vu/flat/64.png
214            Samoa  Oceania  https://www.countryflags.io/ws/flat/64.png

[215 rows x 3 columns]

In [12]:
data_p = pd.read_csv('world_pivot.csv')
data_p

,location,2019-12-31,2020-01-01,2020-01-02,2020-01-03,2020-01-04,2020-01-05,2020-01-06,2020-01-07,2020-01-08,...,2020-05-15,2020-05-16,2020-05-17,2020-05-18,2020-05-19,2020-05-20,2020-05-21,2020-05-22,2020-05-23,2020-05-24
0,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5339.0,6402.0,6402.0,6664.0,7072.0,7653.0,8145.0,8676.0,9216.0,9998.0
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,898.0,916.0,933.0,946.0,948.0,949.0,964.0,969.0,981.0,989.0
2,Algeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6442.0,6629.0,6821.0,7019.0,7201.0,7377.0,7542.0,7728.0,7918.0,8113.0
3,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,761.0,761.0,761.0,761.0,761.0,761.0,762.0,762.0,762.0,762.0
4,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.0,48.0,48.0,48.0,48.0,50.0,52.0,58.0,60.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Vietnam,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,312.0,313.0,318.0,320.0,324.0,324.0,324.0,324.0,324.0,324.0
207,Western Sahara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
208,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,87.0,106.0,124.0,128.0,130.0,167.0,180.0,193.0,205.0,212.0
209,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,654.0,668.0,679.0,753.0,761.0,772.0,832.0,866.0,920.0,920.0
210,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,42.0,44.0,46.0,46.0,46.0,48.0,51.0,56.0,56.0

In [3]:
world_join = pd.merge(data_p,country,how='left',left_on='location',right_on='Country Name',right_index=False)
world_join

NameError: name 'data_p' is not defined

In [15]:
world_join.to_csv('world_join.csv',index=False)

In [114]:
covid = pd.read_csv('../Processd_Data/DXYcity0507Post.csv')
covid

,Date,Latitude,Longitude,city_confirmedCount,city_curedCount,city_deadCount,city_suspectedCount,cityEnglishName
0,05-07,32.716518,108.991299,26.000000,26.0,0.0,0.0,Ankang
1,05-07,34.364581,107.233218,13.000000,13.0,0.0,0.0,Baoji
2,05-07,31.406634,121.485158,22.000000,21.0,1.0,0.0,Baoshan District
3,05-07,40.654916,109.834459,11.000000,11.0,0.0,0.0,Baotou
4,05-07,40.741187,107.382611,8.000000,7.0,1.0,0.0,Bayannur
...,...,...,...,...,...,...,...,...
25527,01-24,37.506217,105.169082,1.000000,0.0,0.0,0.0,Zhongwei
25528,01-24,33.630630,114.642362,1.000000,0.0,0.0,0.0,Zhoukou
25529,01-24,29.987334,122.203036,1.000000,0.0,0.0,0.0,Zhoushan
25530,01-24,22.230520,113.546244,6.571429,0.0,0.0,0.0,Zhuhai
25531,01-24,27.839498,113.148217,1.000000,0.0,0.0,0.0,Zhuzhou

In [6]:
covid_p = covid.pivot(index='cityEnglishName',columns='Date',values='city_confirmedCount')

In [7]:
covid_p

Date,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,02-02,...,04-28,04-29,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07
cityEnglishName,,,,,,,,,,,,,,,,,,,,,
Akesu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ankang,1.0,2.166667,3.0,5.000000,8.0,10.0,10.000000,11.500000,14.000,16.000000,...,26.0,NaN,NaN,26.0,26.0,26.0,26.0,NaN,26.0,26.0
Anqing,1.0,2.800000,4.5,8.000000,8.0,14.0,18.000000,18.000000,29.375,43.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Anshan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000,1.000000,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
Anshun,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zhuzhou,1.0,1.000000,2.0,4.333333,7.0,13.0,18.000000,19.000000,22.000,25.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zibo,NaN,NaN,NaN,2.000000,2.0,4.0,6.666667,8.666667,10.000,11.714286,...,NaN,30.0,30.0,NaN,NaN,NaN,30.0,NaN,30.0,NaN
Zigong,NaN,1.000000,1.0,2.000000,7.0,7.0,7.000000,9.000000,9.000,9.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ziyang,NaN,NaN,NaN,2.000000,2.0,2.0,2.000000,2.000000,2.000,2.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zunyi,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2.500000,NaN,5.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
latlon = covid.groupby(['cityEnglishName','Latitude','Longitude']).size().reset_index()

In [15]:
latlon

    cityEnglishName   Latitude   Longitude   0
0             Akesu  41.166667   80.261243  29
1            Ankang  32.716518  108.991299   3
2            Ankang  32.716518  108.991299   4
3            Ankang  32.716518  108.991299  64
4            Anqing  30.535868  117.104821  38
..              ...        ...         ...  ..
926          Ziyang  30.123598  104.648114   5
927          Ziyang  30.123598  104.648114  61
928          Ziyang  30.123598  104.648114   1
929          Ziyang  30.123598  104.648114   6
930           Zunyi  27.729381  106.923219  39

[931 rows x 4 columns]

In [17]:
covid_p.to_csv('DXYcity0507Post_confirmed_pivot.csv')

In [19]:
covid_array = np.array(covid_p)

In [20]:
covid_array

array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [ 1.        ,  2.16666667,  3.        , ...,         nan,
        26.        , 26.        ],
       [ 1.        ,  2.8       ,  4.5       , ...,         nan,
                nan,         nan],
       ...,
       [        nan,  1.        ,  1.        , ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

In [ ]:
minv = 0
maxv = 0

In [25]:
a = np.where(np.amax(covid_array,axis=1))

In [30]:
maxindex = np.argmax(covid_array,axis=1)

In [31]:
maxindex.shape

(375,)

In [32]:
maxindex

array([  0,  39,  43,   0,   0,   0,   0,  50,   2,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  50,  43,   0,   0,   0,   0,
        43,  44,   2,   0,   0,   0,   0,   0,  51,  52,   0,   0,  35,
         0,   0,   0,  52,   0,  51,   0,  43,   0,   0,  43,   0,  35,
         0,   0,  57,   0,   0,   0,  52,   0,   0,  52,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 100,   0,
        43,  49,   0,   0,   0,   0,   0,  52,   0, 100,   0,  50,   8,
         0,   0,   0,  38,   0,   0,  49,   0,  57,   0,   0,  50,   0,
        43,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  51,   0,   0,  95,   0,   0,   0, 100,   0,   0,   0,
        49,   0,   0,   0,   0,   0,  49,   0,   0,  51,   0,   0,   0,
         0,  95,  95,  49,  51,   0,   0,   0,   0,  49,  52,   0,   0,
         0,  40,   0,   0,  21,   0,   0,   0,   0,   0,  47,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  51,   0,   0,  50,   0,   0,
        51,  43,   0,  45,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        52,   0,   0,  57,   0,  49,   0,  47,   0,   0,   0,  47,   0,
         0,   0,  49,  44,   0,   0,   0,   0,   0,   0,  49,   0,   0,
         0,   0,   0,   0,   0,   8,   0,   0,  51,   0,   0, 100,   0,
         0,   0,   0,   0,   0,  44,   0,  49,  51,  45,  44,  38,   0,
         0,   0,   0,   0, 100,  49,   0,   0,  35, 100,  44,   0,  95,
         0,   0,   0,   0,   0,   0,   2,  57,  52,   0,   0,  47,   0,
         0,  42,  54,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         8,   0,   0,   0,   0,  38,   0,  51,  51,   0,   0,   0,  49,
         0,  95,   0,   0,  47,   0,  50,  39,  44,  51,   0,   0,   0,
        95,  39,  95,   0,   0,   0,   0,  45,  49,   0,   0,   0,  52,
         0,   0,   0,   0,  52,  39,   0,   0, 100,   0,   0,   0,  47,
         0,  51,   0,  95,   0,   0,  12,   0,   0,   0,  51,   0,  51,
         0,   0,   0,   0,   0,   0,   0,  44, 100, 100,   0,  45,   0,
       100,  12,  45,  49, 100,   0,  51,   0,   0,   0,   0])

In [34]:
covid_p0 = covid_p.fillna(0)
covid_p0

Date,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,02-02,...,04-28,04-29,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07
cityEnglishName,,,,,,,,,,,,,,,,,,,,,
Akesu,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ankang,1.0,2.166667,3.0,5.000000,8.0,10.0,10.000000,11.500000,14.000,16.000000,...,26.0,0.0,0.0,26.0,26.0,26.0,26.0,0.0,26.0,26.0
Anqing,1.0,2.800000,4.5,8.000000,8.0,14.0,18.000000,18.000000,29.375,43.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Anshan,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,1.000,1.000000,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0
Anshun,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000,2.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zhuzhou,1.0,1.000000,2.0,4.333333,7.0,13.0,18.000000,19.000000,22.000,25.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zibo,0.0,0.000000,0.0,2.000000,2.0,4.0,6.666667,8.666667,10.000,11.714286,...,0.0,30.0,30.0,0.0,0.0,0.0,30.0,0.0,30.0,0.0
Zigong,0.0,1.000000,1.0,2.000000,7.0,7.0,7.000000,9.000000,9.000,9.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ziyang,0.0,0.000000,0.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,2.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zunyi,0.0,0.000000,0.0,0.000000,0.0,0.0,1.000000,2.500000,0.000,5.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
covid_arr0 = np.array(covid_p0)
maxindex = np.argmax(covid_arr0,axis=1)

In [36]:
maxindex

array([ 15,  28,  24,  67,  14,  28,  15,  14,  15,  30,  22,  16,  14,
        61,  16,  17,  22,  16,  21,  21,  25,  27,   6,  21,  14,  24,
        23,  25,  94,  30,  18,  20,  21,  25,  27,  31,  19,  26,   9,
        83,  59,  15,  85,  22,  21,  23,  21,  24,  18,  21,  18,  69,
        39,  20,  91,  21,  21,  47,  32,  19,  18,  28,  23,  11,  22,
        43,  14,  46,  14,  36,  41,  27,  24,  19,  40,  14,  90,  17,
        26,  34,  17,  22,  21,  35,  15,  18,  11, 104,  17,  29,  53,
        21,  11,  61,  27,   6,  30,  53,  26,  95,  20,  19,  32,  23,
        28,  17,  23,  16,  24,  11,  11,  77,  19,  11,  14,  28,  13,
         7,  76,  22,  43,  15,  40,  19,   7,  41,  26,  23,  98,  41,
        25,  21,  18,  24,  74,  24,  57,  72,  99,  19,   4,  26,  16,
        24,  40,  39,  21,  38,  35,  34,  32,  19,  25,  32,  23,  24,
        23,  26,  17,  23,  68,  16,  14,  11,   7,  23,  23,  19,  64,
        22,  10,   8,  14,  17,   9,  10,  27,  55,  16,  22,  10,  16,
        24,  26,  65,  22,  27,  13,  29,   2,  24,  62,  19,  55,  11,
        53,  28,  19,  98,  21,  58,  31,  26,  21,  29,  21,  22,  34,
        22,   7,  28,  26,   6,  12,  14,  25,  22,  22,  24,   8,  40,
        34,  20,  22,  18,  35,  19,  15,  23,  84,  33,  17,  20,  22,
        15,  10,   7,  14,  25,  32,  19,  18,  23,   8,  24,  20,  14,
        23,  22,  70,  10,  22,  21,  26,  30,  78,  96,  29,  21,  38,
        11,  25,  17,  25,  26,  16,   3,  26,  24,  34,  58,  58,  13,
        29, 100,  47,  58,  25,  16,  69,  14,  31,  28,  25,  25,  23,
        19,  27,  23,  10,  21,  18,  13,  24,  19,  22,  15,  18,  58,
        13,  85,  35,  22,  24,  26,   8,  27,  24,  29,  14,  32,  25,
        32,  17,  36,  27,  24,  13,  24,  30,  27,  17,  14,  13,   0,
        17,  26,  23,  24,  21,  16,  65,  22,  31,  11,  21,  14,  24,
        10,  24,  25,  35,  65,  24,  40,   2,  20,  36,  34,  12,  27,
        39,  18,  15,  22,  14,  35,   5,  22,  63,  55,  23,  48,  16,
        85,  34,  25,  18,  65,  25,  30,  29,   7,  32,  23])

In [39]:
covid_pinf = covid_p.fillna(float("inf"))

In [42]:
covid_pinf = np.array(covid_pinf)

In [43]:
minindex = np.argmin(covid_pinf,axis=1)
minindex

array([15,  0,  0,  8,  9,  4, 15,  0,  0,  8,  1,  4,  2,  3, 12,  3,  5,
       13,  5, 13,  0,  0,  1,  6,  2,  1,  0,  0,  0,  1, 15,  7,  3,  7,
        0,  0,  1,  1,  0,  7,  8,  1,  0,  7,  0,  1,  0,  9, 18,  0, 18,
        0,  2,  1,  0,  1,  7,  5,  0,  2, 18,  0,  1,  7,  2, 11,  7,  1,
        8,  1,  1,  1,  8,  1,  7,  3,  0,  8,  0,  0, 17,  8,  1,  2,  4,
        0,  5,  0,  9,  0,  0,  1, 10,  7,  0,  6,  4,  0,  2,  0,  2,  3,
        0,  2,  0,  6,  9,  4,  1,  2,  3,  4,  1,  6,  4, 18,  3,  3,  2,
        0,  2,  7,  0,  3,  2,  1,  0,  1,  1,  2,  0,  3,  3,  2,  5,  4,
        0,  2, 11,  0,  4,  8,  3,  1,  0,  0,  0,  0, 11,  7,  2,  4,  0,
        0,  5, 10,  3,  0, 13,  3,  0,  7,  2, 11,  4,  3,  0,  1,  4, 11,
        2,  8,  3,  7,  7,  1,  0,  2,  3,  0,  3,  4,  0,  0,  3,  0,  1,
        3,  1,  2,  5, 16,  2,  2,  7,  0,  3, 15,  0,  4,  0,  2,  0,  2,
        2,  2,  0,  1,  1,  7,  0,  0,  6,  1,  2,  7,  1,  7,  0,  5,  3,
        2,  8,  5,  6,  3,  0,  2,  3,  0,  3, 10,  0,  8,  6,  7,  7,  2,
        3,  0,  1,  0,  0,  0,  0,  0,  1,  3,  1,  1,  3,  0,  0,  1,  4,
        0,  0,  0,  7,  0, 11,  3,  7,  3,  5,  7,  0,  0,  0,  1,  1,  0,
       13,  4,  0,  3,  4,  1,  4,  1,  1,  5,  2,  3,  1,  3,  0,  7,  4,
        7,  1,  0, 13,  0,  0,  3, 10, 18,  0, 10,  0,  1, 15,  0,  4,  0,
        0,  0,  0,  2,  1,  2,  0,  0,  0,  7,  3,  1,  1,  0,  0,  8,  2,
        2,  0,  2,  3,  3,  3,  0,  0,  6,  1,  0, 11,  7,  2,  0, 10,  0,
        3,  0,  1,  2,  0,  3,  4,  1,  0, 12,  0,  1,  1,  1,  3,  6,  5,
        3,  0,  0,  0,  2,  0,  2,  0,  0,  0,  0,  0,  1,  0,  3,  1,  3,
        6])

In [46]:
covid_arr0.shape[0]

375

In [54]:
covid_arr0 = np.array(covid_p.fillna(0))

In [55]:
covid_arr0

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  2.16666667,  3.        , ...,  0.        ,
        26.        , 26.        ],
       [ 1.        ,  2.8       ,  4.5       , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  1.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [56]:
for i in range(covid_arr0.shape[0]):
    for j in range(covid_arr0.shape[1]):
        if covid_arr0[i,j] == 0 and j <= minindex[i]:
            covid_arr0[i,j] = covid_arr0[i,minindex[i]]
        elif covid_arr0[i,j] == 0 and j >= maxindex[i]: 
            covid_arr0[i,j] = covid_arr0[i,maxindex[i]]
        elif covid_arr0[i,j] == 0:
            covid_arr0[i,j] = covid_arr0[i,j-1]

In [57]:
covid_arr0

array([[ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 1.        ,  2.16666667,  3.        , ..., 26.        ,
        26.        , 26.        ],
       [ 1.        ,  2.8       ,  4.5       , ..., 83.        ,
        83.        , 83.        ],
       ...,
       [ 1.        ,  1.        ,  1.        , ...,  9.        ,
         9.        ,  9.        ],
       [ 2.        ,  2.        ,  2.        , ...,  4.        ,
         4.        ,  4.        ],
       [ 1.        ,  1.        ,  1.        , ..., 32.        ,
        32.        , 32.        ]])

In [63]:
covid_processed = pd.DataFrame(covid_arr0)

In [65]:
covid_processed.columns = covid_p.columns

In [66]:
covid_processed['city'] = covid_p.index

In [67]:
covid_processed

Date,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,02-02,...,04-29,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,city
0,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000,1.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Akesu
1,1.0,2.166667,3.0,5.000000,8.0,10.0,10.000000,11.500000,14.000,16.000000,...,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,Ankang
2,1.0,2.800000,4.5,8.000000,8.0,14.0,18.000000,18.000000,29.375,43.000000,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,Anqing
3,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000,1.000000,...,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,Anshan
4,2.0,2.000000,2.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,2.000000,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Anshun
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,1.0,1.000000,2.0,4.333333,7.0,13.0,18.000000,19.000000,22.000,25.000000,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,Zhuzhou
371,2.0,2.000000,2.0,2.000000,2.0,4.0,6.666667,8.666667,10.000,11.714286,...,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,Zibo
372,1.0,1.000000,1.0,2.000000,7.0,7.0,7.000000,9.000000,9.000,9.000000,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,Zigong
373,2.0,2.000000,2.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,2.000000,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Ziyang
374,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,2.500000,2.500,5.000000,...,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,Zunyi

In [69]:
covid_processed_latlon = pd.merge(covid_processed,covid,how='left',left_on='city',right_on='cityEnglishName',left_index=False,right_index=False)

In [72]:
covid_processed_final = covid_processed_latlon.groupby('city').mean().reset_index()

In [73]:
covid_processed_final.columns

Index(['city', '01-24', '01-25', '01-26', '01-27', '01-28', '01-29', '01-30',
       '01-31', '02-01',
       ...
       '05-04', '05-05', '05-06', '05-07', 'Latitude', 'Longitude',
       'city_confirmedCount', 'city_curedCount', 'city_deadCount',
       'city_suspectedCount'],
      dtype='object', length=112)

In [80]:
covid_processed_final.drop(columns=['city_confirmedCount', 'city_curedCount', 'city_deadCount','city_suspectedCount'])

,city,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,...,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,Latitude,Longitude
0,Akesu,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,41.166667,80.261243
1,Ankang,1.0,2.166667,3.0,5.000000,8.0,10.0,10.000000,11.500000,14.000,...,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,32.716518,108.991299
2,Anqing,1.0,2.800000,4.5,8.000000,8.0,14.0,18.000000,18.000000,29.375,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,30.535869,117.104821
3,Anshan,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000,...,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,41.108124,122.989970
4,Anshun,2.0,2.000000,2.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,26.249696,105.927781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,Zhuzhou,1.0,1.000000,2.0,4.333333,7.0,13.0,18.000000,19.000000,22.000,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,27.839498,113.148217
371,Zibo,2.0,2.000000,2.0,2.000000,2.0,4.0,6.666667,8.666667,10.000,...,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,36.804783,118.044447
372,Zigong,1.0,1.000000,1.0,2.000000,7.0,7.0,7.000000,9.000000,9.000,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,29.342001,104.776159
373,Ziyang,2.0,2.000000,2.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,30.123598,104.648114
374,Zunyi,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,2.500000,2.500,...,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,27.729382,106.923219

In [81]:
covid_processed_final.to_csv('DXYcity0507_confirmed.csv')

In [7]:
# cure
cure = covid.pivot(index='cityEnglishName',columns='Date',values='city_curedCount')

# fillna with 0/inf
cure0 = np.array(cure.fillna(0))
cureinf = np.array(cure.fillna(float('inf')))

# find max, min index
cure_maxid = np.argmax(cure0,axis=1)
cure_minid = np.argmin(cureinf,axis=1)

# populate na
for i in range(cure0.shape[0]):
    for j in range(cure0.shape[1]):
        if cure0[i,j] == 0 and j <= cure_minid[i]:
            cure0[i,j] = cure0[i,cure_minid[i]]
        elif cure0[i,j] == 0 and j >= cure_maxid[i]: 
            cure0[i,j] = cure0[i,cure_maxid[i]]
        elif cure0[i,j] == 0:
            cure0[i,j] = cure0[i,j-1]

# add city column
cure_processed = pd.DataFrame(cure0)
cure_processed.columns = cure.columns
cure_processed['city'] = cure.index

In [13]:
cure_processed_latlon = pd.merge(cure_processed,covid,how='left',left_on='city',right_on='cityEnglishName',left_index=False,right_index=False)
cure_processed_final = cure_processed_latlon.groupby('city').mean().reset_index()
cure_processed_final = cure_processed_final.drop(columns=['city_confirmedCount', 'city_curedCount', 'city_deadCount','city_suspectedCount'])

In [14]:
cure_processed_final.to_csv('DXYcity0507_cured.csv')

In [141]:
# confirm2 with last index
confirm = covid.pivot(index='cityEnglishName',columns='Date',values='city_confirmedCount')

# get valid index
test=confirm.T.reset_index().drop(columns=['Date'])
last_index = test.apply(pd.Series.last_valid_index)
 
# fillna with 0/inf
confirm0 = np.array(confirm.fillna(0))
confirminf = np.array(confirm.fillna(float('inf')))

# find max, min index
confirm_minid = np.argmin(confirminf,axis=1)

# populate na
for i in range(confirm0.shape[0]):
    for j in range(confirm0.shape[1]):
        if confirm0[i,j] == 0 and j <= confirm_minid[i]:
            confirm0[i,j] = confirm0[i,confirm_minid[i]]
        elif confirm0[i,j] == 0 and j >= last_index[i]: 
            confirm0[i,j] = confirm0[i,last_index[i]]
        elif confirm0[i,j] == 0:
            confirm0[i,j] = confirm0[i,j-1]

# add city column
confirm_processed = pd.DataFrame(confirm0)
confirm_processed.columns = confirm.columns
confirm_processed['city'] = confirm.index

# add coordinates
confirm_processed_latlon = pd.merge(confirm_processed,covid,how='left',left_on='city',right_on='cityEnglishName',left_index=False,right_index=False)
confirm_processed_final = confirm_processed_latlon.groupby('city').mean().reset_index()
confirm_processed_final = confirm_processed_final.drop(columns=['city_confirmedCount', 'city_curedCount', 'city_deadCount','city_suspectedCount'])

# save
confirm_processed_final.to_csv('DXYcity0507_confirmed2.csv')

In [151]:
confirm_processed_finalt = confirm_processed_final.T

In [153]:
confirm_processed_finalt.to_csv('DXYcity0507_confirmed2_t.csv')

In [155]:
confirm_processed_final1 = pd.read_csv('DXYcity0507_confirmed.csv')
confirm_processed_final1t = confirm_processed_final.T
confirm_processed_final1t.to_csv('DXYcity0507_confirmed_t.csv')

In [123]:
sum(abs(confirm_processed['05-07']-confirm_processed_final1['05-07']))

90.25

In [130]:
# confirm2 with last index
cure = covid.pivot(index='cityEnglishName',columns='Date',values='city_curedCount')

# get valid index
test=cure.T.reset_index().drop(columns=['Date'])
last_index = test.apply(pd.Series.last_valid_index)
 
# fillna with 0/inf
cure0 = np.array(cure.fillna(0))
cureinf = np.array(cure.fillna(float('inf')))

# find max, min index
cure_minid = np.argmin(cureinf,axis=1)

# populate na
for i in range(cure0.shape[0]):
    for j in range(cure0.shape[1]):
        if cure0[i,j] == 0 and j <= cure_minid[i]:
            cure0[i,j] = cure0[i,cure_minid[i]]
        elif cure0[i,j] == 0 and j >= last_index[i]: 
            cure0[i,j] = cure0[i,last_index[i]]
        elif cure0[i,j] == 0:
            cure0[i,j] = cure0[i,j-1]

# add city column
cure_processed = pd.DataFrame(cure0)
cure_processed.columns = cure.columns
cure_processed['city'] = cure.index

# add coordinates
cure_processed_latlon = pd.merge(cure_processed,covid,how='left',left_on='city',right_on='cityEnglishName',left_index=False,right_index=False)
cure_processed_final = cure_processed_latlon.groupby('city').mean().reset_index()
cure_processed_final = cure_processed_final.drop(columns=['city_confirmedCount', 'city_curedCount', 'city_deadCount','city_suspectedCount'])

# save
cure_processed_final.to_csv('DXYcity0507_cured2.csv')
cure_processed_final

,city,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,...,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,Latitude,Longitude
0,Akesu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,41.166667,80.261243
1,Ankang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,32.716518,108.991299
2,Anqing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,30.535869,117.104821
3,Anshan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,41.108124,122.989970
4,Anshun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,26.249696,105.927781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,Zhuzhou,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,27.839498,113.148217
371,Zibo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29.0,29.0,29.0,29.0,29.0,29.0,29.0,29.0,36.804783,118.044447
372,Zigong,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,29.342001,104.776159
373,Ziyang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,30.123598,104.648114
374,Zunyi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,27.729382,106.923219

In [157]:
cure_processed_finalt = cure_processed_final.T
cure_processed_finalt.to_csv('DXYcity0507_cured2_t.csv')
cure_processed_final1t = cure_processed_final1.T
cure_processed_final1t.to_csv('DXYcity0507_cured_t.csv')

In [132]:
cure_processed_final1 = pd.read_csv('DXYcity0507_cured.csv')
cure_processed_final1

,Unnamed: 0,city,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,...,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,Latitude,Longitude
0,0,Akesu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,41.166667,80.261243
1,1,Ankang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,32.716518,108.991299
2,2,Anqing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,30.535869,117.104821
3,3,Anshan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,41.108124,122.989970
4,4,Anshun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,26.249696,105.927781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,370,Zhuzhou,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,27.839498,113.148217
371,371,Zibo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29.0,29.0,29.0,29.0,29.0,29.0,29.0,29.0,36.804783,118.044447
372,372,Zigong,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,29.342001,104.776159
373,373,Ziyang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,30.123598,104.648114
374,374,Zunyi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,27.729382,106.923219

In [134]:
sum(abs(cure_processed_final['05-07']-cure_processed_final1['05-07']))

828.5

In [136]:
cure_processed_final['05-07'][300]

46464.0

In [139]:
cure_processed_final1['05-07'][300]-cure_processed_final['05-07'][300]

819.0

In [147]:
# confirm2 with last index
dead = covid.pivot(index='cityEnglishName',columns='Date',values='city_deadCount')

# get valid index
test=dead.T.reset_index().drop(columns=['Date'])
last_index = test.apply(pd.Series.last_valid_index)
 
# fillna with 0/inf
dead0 = np.array(dead.fillna(0))
deadinf = np.array(dead.fillna(float('inf')))

# find max, min index
dead_minid = np.argmin(deadinf,axis=1)

# populate na
for i in range(dead0.shape[0]):
    for j in range(dead0.shape[1]):
        if dead0[i,j] == 0 and j <= dead_minid[i]:
            dead0[i,j] = dead0[i,dead_minid[i]]
        elif dead0[i,j] == 0 and j >= last_index[i]: 
            dead0[i,j] = dead0[i,last_index[i]]
        elif dead0[i,j] == 0:
            dead0[i,j] = dead0[i,j-1]

# add city column
dead_processed = pd.DataFrame(dead0)
dead_processed.columns = dead.columns
dead_processed['city'] = dead.index

# add coordinates
dead_processed_latlon = pd.merge(dead_processed,covid,how='left',left_on='city',right_on='cityEnglishName',left_index=False,right_index=False)
dead_processed_final = dead_processed_latlon.groupby('city').mean().reset_index()
dead_processed_final = dead_processed_final.drop(columns=['city_confirmedCount', 'city_curedCount', 'city_deadCount','city_suspectedCount'])

# save
dead_processed_final.to_csv('DXYcity0507_dead2.csv')
dead_processed_final

,city,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,...,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,Latitude,Longitude
0,Akesu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.166667,80.261243
1,Ankang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.716518,108.991299
2,Anqing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.535869,117.104821
3,Anshan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.108124,122.989970
4,Anshun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.249696,105.927781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,Zhuzhou,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.839498,113.148217
371,Zibo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,36.804783,118.044447
372,Zigong,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.342001,104.776159
373,Ziyang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.123598,104.648114
374,Zunyi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.729382,106.923219

In [158]:
dead_processed_finalt = dead_processed_final.T
dead_processed_finalt.to_csv('DXYcity0507_dead2_t.csv')
dead_processed_final1t = cure_processed_final1.T
dead_processed_final1t.to_csv('DXYcity0507_dead_t.csv')

In [148]:
dead_processed_final1 = pd.read_csv('DXYcity0507_dead.csv')
sum(abs(dead_processed_final['05-07']-dead_processed_final1['05-07']))

1.2916666666666656

In [149]:
dead_processed_final1['05-07'][300]

3869.0

In [150]:
dead_processed_final['05-07'][300]

3869.0

In [17]:
dead_processed_final

,city,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,...,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,Latitude,Longitude
0,Akesu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.166667,80.261243
1,Ankang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.716518,108.991299
2,Anqing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.535869,117.104821
3,Anshan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.108124,122.989970
4,Anshun,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.249696,105.927781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,Zhuzhou,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.839498,113.148217
371,Zibo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,36.804783,118.044447
372,Zigong,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.342001,104.776159
373,Ziyang,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.123598,104.648114
374,Zunyi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.729382,106.923219

In [184]:
confirm_chart = pd.DataFrame(np.sum(confirm0,axis=0))
confirm_chart = confirm_chart.T
confirm_chart.columns = confirm.columns
confirm_chart['city'] = 'All'

In [187]:
confirm_top5 = confirm_processed.nlargest(5,'05-07')

In [190]:
confirm_chart = pd.concat([confirm_chart,confirm_top5])

In [196]:
confirm_chart = confirm_chart.T

In [200]:
confirm_chart.to_csv('covid_confirmed_chart.csv')

In [205]:
confirm_chart.T.to_csv('covid_confirmed_chart_t.csv',index=False)

In [201]:
# cure chart data
cure_chart = pd.DataFrame(np.sum(cure0,axis=0))
cure_chart = cure_chart.T
cure_chart.columns = cure.columns
cure_chart['city'] = 'All'

cure_top5 = cure_processed.nlargest(5,'05-07')
cure_chart = pd.concat([cure_chart,cure_top5])
cure_chart = cure_chart.T
cure_chart

           0        300       314        122       145    70
Date
01-24     19.9  12.6429         0          0         0      0
01-25  41.1389  31.8889         0          0         0      0
01-26  50.1929  38.6667         0    1.66667         0      0
01-27  55.4626  41.8182  0.454545    2.18182  0.181818      0
01-28  63.8545  44.6667  0.454545          2         1      0
...        ...      ...       ...        ...       ...    ...
05-04    75476    46464      3389       2782      1528   1335
05-05    75484    46464      3389       2782      1528   1335
05-06  75495.5    46464      3389       2782      1528   1335
05-07    75402    46464      3389       2782      1528   1335
city       All    Wuhan   Xiaogan  Huanggang  Jingzhou  Ezhou

[106 rows x 6 columns]

In [202]:
cure_chart.to_csv('covid_cured_chart.csv')

In [206]:
cure_chart.T.to_csv('covid_cured_chart_t.csv',index=False)

In [204]:
# dead chart data
dead_chart = pd.DataFrame(np.sum(dead0,axis=0))
dead_chart = dead_chart.T
dead_chart.columns = dead.columns
dead_chart['city'] = 'All'

dead_top5 = dead_processed.nlargest(5,'05-07')
dead_chart = pd.concat([dead_chart,dead_top5])
dead_chart = dead_chart.T
dead_chart.to_csv('covid_dead_chart.csv')
dead_chart

           0        300       314        122    70        145
Date
01-24  6.23377  1.64286         0          0      0         0
01-25  42.3333  36.3333         0          0      0         0
01-26    54.75  43.8333         0    1.66667      0   1.66667
01-27  76.5455  61.3636  0.454545    3.45455      0         2
01-28    104.2       85         1          4      0         2
...        ...      ...       ...        ...    ...       ...
05-04  4615.66     3869       129        125     59        52
05-05  4615.53     3869       129        125     59        52
05-06  4615.33     3869       129        125     59        52
05-07     4615     3869       129        125     59        52
city       All    Wuhan   Xiaogan  Huanggang  Ezhou  Jingzhou

[106 rows x 6 columns]

In [207]:
dead_chart.T.to_csv('covid_dead_chart_t.csv',index=False)

In [161]:
cities = pd.DataFrame(dead_processed_final.city)

In [165]:
cities['color'] = '#666666'

In [166]:
cities

        city    color
0      Akesu  #666666
1     Ankang  #666666
2     Anqing  #666666
3     Anshan  #666666
4     Anshun  #666666
..       ...      ...
370  Zhuzhou  #666666
371     Zibo  #666666
372   Zigong  #666666
373   Ziyang  #666666
374    Zunyi  #666666

[375 rows x 2 columns]

In [19]:
# cure
confirm = covid.pivot(index='cityEnglishName',columns='Date',values='city_confirmedCount')

# fillna with 0/inf
confirm0 = np.array(confirm.fillna(0))
confirminf = np.array(confirm.fillna(float('inf')))

# find max, min index
confirm_maxid = np.argmax(confirm0,axis=1)
confirm_minid = np.argmin(confirminf,axis=1)

# populate na
for i in range(confirm0.shape[0]):
    for j in range(confirm0.shape[1]):
        if confirm0[i,j] == 0 and j <= confirm_minid[i]:
            confirm0[i,j] = confirm0[i,confirm_minid[i]]
        elif confirm0[i,j] == 0 and j >= confirm_maxid[i]: 
            confirm0[i,j] = confirm0[i,confirm_maxid[i]]
        elif confirm0[i,j] == 0:
            confirm0[i,j] = confirm0[i,j-1]

# add city column
confirm_processed = pd.DataFrame(confirm0)
confirm_processed.columns = confirm.columns
confirm_processed['city'] = confirm.index

# join lat lon
confirm_processed_latlon = pd.merge(confirm_processed,covid,how='left',left_on='city',right_on='cityEnglishName',left_index=False,right_index=False)
confirm_processed_final = confirm_processed_latlon.groupby('city').mean().reset_index()
confirm_processed_final = confirm_processed_final.drop(columns=['city_confirmedCount', 'city_curedCount', 'city_deadCount','city_suspectedCount'])

# save
confirm_processed_final.to_csv('DXYcity0507_confirmed.csv')

In [20]:
confirm_processed_final

,city,01-24,01-25,01-26,01-27,01-28,01-29,01-30,01-31,02-01,...,04-30,05-01,05-02,05-03,05-04,05-05,05-06,05-07,Latitude,Longitude
0,Akesu,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,41.166667,80.261243
1,Ankang,1.0,2.166667,3.0,5.000000,8.0,10.0,10.000000,11.500000,14.000,...,26.0,26.0,26.0,26.0,26.0,26.0,26.0,26.0,32.716518,108.991299
2,Anqing,1.0,2.800000,4.5,8.000000,8.0,14.0,18.000000,18.000000,29.375,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,30.535869,117.104821
3,Anshan,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.000000,1.000,...,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,41.108124,122.989970
4,Anshun,2.0,2.000000,2.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,26.249696,105.927781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,Zhuzhou,1.0,1.000000,2.0,4.333333,7.0,13.0,18.000000,19.000000,22.000,...,80.0,80.0,80.0,80.0,80.0,80.0,80.0,80.0,27.839498,113.148217
371,Zibo,2.0,2.000000,2.0,2.000000,2.0,4.0,6.666667,8.666667,10.000,...,30.0,30.0,30.0,30.0,30.0,30.0,30.0,30.0,36.804783,118.044447
372,Zigong,1.0,1.000000,1.0,2.000000,7.0,7.0,7.000000,9.000000,9.000,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,29.342001,104.776159
373,Ziyang,2.0,2.000000,2.0,2.000000,2.0,2.0,2.000000,2.000000,2.000,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,30.123598,104.648114
374,Zunyi,1.0,1.000000,1.0,1.000000,1.0,1.0,1.000000,2.500000,2.500,...,32.0,32.0,32.0,32.0,32.0,32.0,32.0,32.0,27.729382,106.923219

In [110]:
sars = pd.read_csv('../Processd_Data/sars_data.csv')

In [111]:
sars

,provinceEnglishName,DateTime,city_confirmIncrease,city_confirmedCount,city_curedIncrease,city_curedCount,city_deadIncrease,city_deadCount,city_suspectedIncrease,city_suspectedClear,city_suspectedCount,city_confirmIncrease_fromSuspected,city_confirmClear,city_doctorClear,Note,Ref,city_doctorIncrease,city_doctorCount
0,all,2003-03-31,NaN,1190.0,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,all,2003-04-02,NaN,1220.0,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,#ERROR!,NaN,NaN,NaN
2,all,2003-04-06,NaN,1268.0,NaN,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,all,2003-04-09,NaN,1290.0,NaN,1025.0,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,all,2003-04-15 12:00,NaN,1435.0,NaN,1094.0,NaN,64.0,NaN,NaN,NaN,NaN,NaN,NaN,4月10日以来，全国非典型肺炎的病人数有所增加，其中，山西增加了近50例，原因主要是，卫生部...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301,Zhejiang,2003-05-27 10:00,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0
1302,Zhejiang,2003-05-28 10:00,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0
1303,Zhejiang,2003-05-29 10:00,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0
1304,Zhejiang,2003-05-30 10:00,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0
1305,Zhejiang,2003-05-31 10:00,0.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0

In [5]:
confirm = sars.pivot(index='provinceEnglishName',columns='DateTime',values='city_confirmedCount')
confirm

DateTime,2003-03-31,2003-04-02,2003-04-06,2003-04-09,2003-04-15 12:00,2003-04-18,2003-04-21,2003-04-22 20:00,2003-04-23 20:00,2003-04-24 20:00,...,2003-07-15 10:00,2003-07-16 10:00,2003-07-17 10:00,2003-07-27 10:00,2003-07-30 10:00,2003-08-02 10:00,2003-08-13 10:00,2003-08-14 10:00,2003-08-15 10:00,2003-08-16 10:00
provinceEnglishName,,,,,,,,,,,,,,,,,,,,,
Anhui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Beijing,12.0,NaN,19.0,22.0,37.0,NaN,482.0,693.0,774.0,877.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chongqing,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fujian,NaN,NaN,NaN,NaN,3.0,NaN,NaN,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gansu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guangdong,1153.0,NaN,1203.0,1213.0,1273.0,NaN,1317.0,1344.0,1359.0,1374.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guangxi,11.0,NaN,11.0,12.0,12.0,NaN,14.0,15.0,16.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guizhou,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hebei,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.0,6.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Heilongjiang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Henan,NaN,NaN,NaN,NaN,NaN,NaN,3.0,6.0,8.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hubei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hunan,7.0,NaN,6.0,6.0,6.0,NaN,6.0,6.0,6.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inner Mongolia,NaN,NaN,NaN,NaN,17.0,NaN,30.0,36.0,47.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jiangsu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jiangxi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jilin,NaN,NaN,NaN,NaN,NaN,NaN,3.0,7.0,7.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Liaoning,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ningxia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shaanxi,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shandong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shanghai,0.0,NaN,1.0,1.0,1.0,NaN,2.0,2.0,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shanxi,4.0,NaN,24.0,32.0,82.0,NaN,120.0,157.0,162.0,173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sichuan,3.0,NaN,4.0,4.0,4.0,NaN,8.0,8.0,8.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tianjin,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,8.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Xinjiang,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zhejiang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
all,1190.0,1220.0,1268.0,1290.0,1435.0,1807.0,2001.0,2305.0,2422.0,2601.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
test=confirm.T.reset_index().drop(columns=['DateTime'])

In [31]:
valid_index = test.apply(pd.Series.last_valid_index)

In [32]:
valid_index

provinceEnglishName
Anhui             45
Beijing           68
Chongqing         45
Fujian            45
Gansu             45
Guangdong         70
Guangxi           51
Guizhou            8
Hebei             58
Heilongjiang      45
Henan             45
Hubei             52
Hunan             45
Inner Mongolia    58
Jiangsu           45
Jiangxi           45
Jilin             50
Liaoning          67
Ningxia           45
Shaanxi           45
Shandong          45
Shanghai          56
Shanxi            58
Sichuan           68
Tianjin           50
Xinjiang          45
Zhejiang          45
all               70
dtype: int64

68

In [33]:
confirm0 = np.array(confirm.fillna(0))

In [35]:
confirm0[1][68]

2521.0

In [79]:
# fillna with 0/inf
confirm0 = np.array(confirm.fillna(0))
confirminf = np.array(confirm.fillna(float('inf')))

# find max, min index
# confirm_maxid = np.argmax(confirm0,axis=1)
confirm_minid = np.argmin(confirminf,axis=1)

# populate na
for i in range(confirm0.shape[0]):
    for j in range(confirm0.shape[1]):
        if confirm0[i,j] == 0 and j <= confirm_minid[i]:
            confirm0[i,j] = confirm0[i,confirm_minid[i]]
        elif confirm0[i,j] == 0 and j >= valid_index[i]: 
            confirm0[i,j] = confirm0[i,valid_index[i]]
        elif confirm0[i,j] == 0:
            confirm0[i,j] = confirm0[i,j-1]

# add city column
confirm_processed = pd.DataFrame(confirm0)
confirm_processed.columns = confirm.columns
confirm_processed['province'] = confirm.index

In [80]:
confirm_processed

DateTime,2003-03-31,2003-04-02,2003-04-06,2003-04-09,2003-04-15 12:00,2003-04-18,2003-04-21,2003-04-22 20:00,2003-04-23 20:00,2003-04-24 20:00,...,2003-07-16 10:00,2003-07-17 10:00,2003-07-27 10:00,2003-07-30 10:00,2003-08-02 10:00,2003-08-13 10:00,2003-08-14 10:00,2003-08-15 10:00,2003-08-16 10:00,province
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,Anhui
1,12.0,12.0,19.0,22.0,37.0,37.0,482.0,693.0,774.0,877.0,...,2521.0,2521.0,2521.0,2521.0,2521.0,2521.0,2521.0,2521.0,2521.0,Beijing
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Chongqing
3,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,Fujian
4,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,Gansu
5,1153.0,1153.0,1203.0,1213.0,1273.0,1273.0,1317.0,1344.0,1359.0,1374.0,...,1512.0,1512.0,1512.0,1512.0,1512.0,1512.0,1512.0,1512.0,1512.0,Guangdong
6,11.0,11.0,11.0,12.0,12.0,12.0,14.0,15.0,16.0,16.0,...,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,22.0,Guangxi
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Guizhou
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,18.0,...,215.0,215.0,215.0,215.0,215.0,215.0,215.0,215.0,215.0,Hebei
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Heilongjiang
10,3.0,3.0,3.0,3.0,3.0,3.0,3.0,6.0,8.0,9.0,...,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,Henan
11,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,Hubei
12,7.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,Hunan
13,17.0,17.0,17.0,17.0,17.0,17.0,30.0,36.0,47.0,70.0,...,282.0,282.0,282.0,282.0,282.0,282.0,282.0,282.0,282.0,Inner Mongolia
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,Jiangsu
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Jiangxi
16,3.0,3.0,3.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,...,35.0,35.0,35.0,35.0,35.0,35.0,35.0,35.0,35.0,Jilin
17,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,...,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,7.0,Liaoning
18,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,Ningxia
19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,Shaanxi
20,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,Shandong
21,0.0,0.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,Shanghai
22,4.0,4.0,24.0,32.0,82.0,82.0,120.0,157.0,162.0,173.0,...,448.0,448.0,448.0,448.0,448.0,448.0,448.0,448.0,448.0,Shanxi
23,3.0,3.0,4.0,4.0,4.0,4.0,8.0,8.0,8.0,9.0,...,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,Sichuan
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,8.0,21.0,...,175.0,175.0,175.0,175.0,175.0,175.0,175.0,175.0,175.0,Tianjin
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Xinjiang
26,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,Zhejiang
27,1190.0,1220.0,1268.0,1290.0,1435.0,1807.0,2001.0,2305.0,2422.0,2601.0,...,5327.0,5327.0,5327.0,5327.0,5327.0,5327.0,5327.0,5327.0,5327.0,all

In [56]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(country_bias="China")

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `country_bias` argument of the Nominatim.__init__ is deprecated and will be removed in geopy 2.0. Use Nominatim.geocode(country_codes='China') instead.

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: Using Nominatim with the default "geopy/1.22.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.

In [46]:
province = confirm_processed['province']

In [61]:
a = geolocator.geocode("Beijing")

In [63]:
a.latitude

39.906217

In [70]:
from geopy.geocoders import Nominatim
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

geolocator = Nominatim(user_agent="myapp",country_bias="China",timeout=10)

# from geopy.extra.rate_limiter import RateLimiter
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
confirm_processed['location'] = confirm_processed['province'].apply(geocode)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: `country_bias` argument of the Nominatim.__init__ is deprecated and will be removed in geopy 2.0. Use Nominatim.geocode(country_codes='China') instead.
  """

In [73]:
confirm_processed['latitude'] = confirm_processed['location'].apply(lambda loc: loc.latitude if loc else None)
confirm_processed['longitude'] = confirm_processed['location'].apply(lambda loc: loc.longitude if loc else None)

In [77]:
confirm_processed_final = confirm_processed.drop(columns=['location'])

# save
confirm_processed_final.to_csv('SARS_confirmed.csv',index=False)

In [89]:
# cure
# cure = sars.pivot(index='provinceEnglishName',columns='DateTime',values='city_curedCount')

# get valid index
test=cure.T.reset_index().drop(columns=['DateTime'])
last_index = test.apply(pd.Series.last_valid_index)
 
# fillna with 0/inf
cure0 = np.array(cure.fillna(0))
cureinf = np.array(cure.fillna(float('inf')))

# find max, min index
cure_minid = np.argmin(cureinf,axis=1)

# populate na
for i in range(cure0.shape[0]):
    for j in range(cure0.shape[1]):
        if cure0[i,j] == 0 and j <= cure_minid[i]:
            cure0[i,j] = cure0[i,cure_minid[i]]
        elif cure0[i,j] == 0 and j >= last_index[i]: 
            cure0[i,j] = cure0[i,last_index[i]]
        elif cure0[i,j] == 0:
            cure0[i,j] = cure0[i,j-1]

# add city column
cure_processed = pd.DataFrame(cure0)
cure_processed.columns = cure.columns
cure_processed['province'] = cure.index

# add coordinates
geolocator = Nominatim(user_agent="myapp2",country_bias="China",timeout=10)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

cure_processed['location'] = cure_processed['province'].apply(geocode)
cure_processed['latitude'] = cure_processed['location'].apply(lambda loc: loc.latitude if loc else None)
cure_processed['longitude'] = cure_processed['location'].apply(lambda loc: loc.longitude if loc else None)

# drop location column
cure_processed_final = cure_processed.drop(columns=['location'])

# save
cure_processed_final.to_csv('SARS_cured.csv',index=False)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:31: DeprecationWarning: `country_bias` argument of the Nominatim.__init__ is deprecated and will be removed in geopy 2.0. Use Nominatim.geocode(country_codes='China') instead.

In [87]:
cure = sars.pivot(index='provinceEnglishName',columns='DateTime',values='city_curedCount')
cure

DateTime,2003-03-31,2003-04-02,2003-04-06,2003-04-09,2003-04-15 12:00,2003-04-18,2003-04-21,2003-04-22 20:00,2003-04-23 20:00,2003-04-24 20:00,...,2003-07-15 10:00,2003-07-16 10:00,2003-07-17 10:00,2003-07-27 10:00,2003-07-30 10:00,2003-08-02 10:00,2003-08-13 10:00,2003-08-14 10:00,2003-08-15 10:00,2003-08-16 10:00
provinceEnglishName,,,,,,,,,,,,,,,,,,,,,
Anhui,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Beijing,NaN,NaN,NaN,1.0,8.0,NaN,43.0,55.0,64.0,73.0,...,2307.0,2308.0,2309.0,NaN,2310.0,2311.0,2312.0,2315.0,2318.0,2321.0
Chongqing,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fujian,NaN,NaN,NaN,NaN,0.0,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gansu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guangdong,NaN,NaN,NaN,1004.0,1063.0,NaN,1136.0,1146.0,1159.0,1173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guangxi,NaN,NaN,NaN,8.0,8.0,NaN,8.0,8.0,8.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Guizhou,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hebei,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Heilongjiang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Henan,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hubei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hunan,NaN,NaN,NaN,5.0,5.0,NaN,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inner Mongolia,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jiangsu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jiangxi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Jilin,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Liaoning,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ningxia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shaanxi,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shandong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shanghai,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shanxi,NaN,NaN,NaN,4.0,7.0,NaN,6.0,13.0,14.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sichuan,NaN,NaN,NaN,3.0,3.0,NaN,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tianjin,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Xinjiang,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zhejiang,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
all,NaN,NaN,NaN,1025.0,1094.0,1165.0,1201.0,1231.0,1254.0,1227.0,...,4945.0,4946.0,4947.0,NaN,4948.0,4949.0,4950.0,4953.0,4956.0,4959.0

DateTime,2003-03-31,2003-04-02,2003-04-06,2003-04-09,2003-04-15 12:00,2003-04-18,2003-04-21,2003-04-22 20:00,2003-04-23 20:00,2003-04-24 20:00,...,2003-07-30 10:00,2003-08-02 10:00,2003-08-13 10:00,2003-08-14 10:00,2003-08-15 10:00,2003-08-16 10:00,province,location,latitude,longitude
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.0,9.0,9.0,9.0,Anhui,"(安徽省, China 中国, (32.0, 117.0))",32.000000,117.000000
1,1.0,1.0,1.0,1.0,8.0,8.0,43.0,55.0,64.0,73.0,...,2310.0,2311.0,2312.0,2315.0,2318.0,2321.0,Beijing,"(北京市, 东城区, 北京市, 100010, China 中国, (39.906217, ...",39.906217,116.391276
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Chongqing,"(重庆市, 渝中区 (Yuzhong), 重庆市中心, 重庆市, 400014, China...",29.558571,106.549282
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,...,3.0,3.0,3.0,3.0,3.0,3.0,Fujian,"(福建省, China 中国, (26.5450001, 117.842778))",26.545000,117.842778
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,5.0,5.0,5.0,5.0,5.0,Gansu,"(甘肃省, China 中国, (38.0000001, 101.9999999))",38.000000,102.000000
5,1004.0,1004.0,1004.0,1004.0,1063.0,1063.0,1136.0,1146.0,1159.0,1173.0,...,1447.0,1447.0,1447.0,1447.0,1447.0,1447.0,Guangdong,"(广东省, China 中国, (23.1357694, 113.1982688))",23.135769,113.198269
6,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,...,17.0,17.0,17.0,17.0,17.0,17.0,Guangxi,"(广西壮族自治区, China 中国, (24.0, 109.0))",24.000000,109.000000
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Guizhou,"(贵州省, China 中国, (27.0, 107.0))",27.000000,107.000000
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,202.0,202.0,202.0,202.0,202.0,202.0,Hebei,"(河北省, China 中国, (39.0000001, 116.0))",39.000000,116.000000
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Heilongjiang,"(黑龙江省, China 中国, (48.0000047, 127.999992))",48.000005,127.999992
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,11.0,11.0,11.0,Henan,"(河南省, China 中国, (34.0000001, 113.9999999))",34.000000,114.000000
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,6.0,6.0,6.0,6.0,Hubei,"(湖北省, China 中国, (31.15172525, 112.878322246560...",31.151725,112.878322
12,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,5.0,5.0,Hunan,"(湖南省, China 中国, (27.9995878, 112.009538))",27.999588,112.009538
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,245.0,245.0,245.0,245.0,245.0,245.0,Inner Mongolia,"(内蒙古自治区, China 中国, (43.2443242, 114.3251664))",43.244324,114.325166
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,3.0,3.0,3.0,3.0,Jiangsu,"(江苏省, China 中国, (33.0000001, 119.9999999))",33.000000,120.000000
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Jiangxi,"(江西省, China 中国, (28.0, 116.0))",28.000000,116.000000
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,21.0,21.0,21.0,21.0,21.0,Jilin,"(吉林省, China 中国, (42.9995032, 125.9816054))",42.999503,125.981605
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,Liaoning,"(辽宁省, China 中国, (40.9975197, 122.9955469))",40.997520,122.995547
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,4.0,4.0,4.0,4.0,4.0,Ningxia,"(宁夏回族自治区, China 中国, (37.0000001, 105.9999999))",37.000000,106.000000
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,11.0,11.0,11.0,11.0,11.0,Shaanxi,"(陕西省, China 中国, (36.0, 109.0))",36.000000,109.000000
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Shandong,"(山东省, China 中国, (36.0000001, 118.9999999))",36.000000,119.000000
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,3.0,3.0,3.0,3.0,3.0,Shanghai,"(上海市, 黄浦区, 上海市, 200010, China 中国, (31.2252985,...",31.225299,121.489050
22,4.0,4.0,4.0,4.0,7.0,7.0,6.0,13.0,14.0,14.0,...,403.0,403.0,403.0,403.0,403.0,403.0,Shanxi,"(山西省, China 中国, (37.0, 112.0))",37.000000,112.000000
23,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,17.0,17.0,17.0,17.0,17.0,17.0,Sichuan,"(四川省, China 中国, (30.5000001, 102.4999999))",30.500000,102.500000
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,132.0,132.0,132.0,132.0,132.0,132.0,Tianjin,"(天津市, 和平区 (Heping), 天津市, 300010, China 中国, (39...",39.123564,117.198078
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Xinjiang,"(新疆维吾尔自治区, China 中国, (41.7574769, 87.167384230...",41.757477,87.167384
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Zhejiang,"(浙江省, China 中国, (29.0000001, 119.9999999))",29.000000,120.000000
27,1025.0,1025.0,1025.0,1025.0,1094.0,1165.0,1201.0,1231.0,1254.0,1227.0,...,4948.0,4949.0,4950.0,4953.0,4956.0,4959.0,all,"(Shqipëria, (41.000028, 19.9999619))",41.000028,19.999962

In [112]:
# cure
dead = sars.pivot(index='provinceEnglishName',columns='DateTime',values='city_deadCount')

# get valid index
test=dead.T.reset_index().drop(columns=['DateTime'])
last_index = test.apply(pd.Series.last_valid_index)
 
# fillna with 0/inf
dead0 = np.array(dead.fillna(0))
deadinf = np.array(dead.fillna(float('inf')))

# find max, min index
dead_minid = np.argmin(deadinf,axis=1)

# populate na
for i in range(dead0.shape[0]):
    for j in range(dead0.shape[1]):
        if dead0[i,j] == 0 and j <= dead_minid[i]:
            dead0[i,j] = dead0[i,dead_minid[i]]
        elif dead0[i,j] == 0 and j >= last_index[i]: 
            dead0[i,j] = dead0[i,last_index[i]]
        elif dead0[i,j] == 0:
            dead0[i,j] = dead0[i,j-1]

# add city column
dead_processed = pd.DataFrame(dead0)
dead_processed.columns = dead.columns
dead_processed['province'] = dead.index

# add coordinates
geolocator = Nominatim(user_agent="myapp2",country_bias="China",timeout=10)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

dead_processed['location'] = dead_processed['province'].apply(geocode)
dead_processed['latitude'] = dead_processed['location'].apply(lambda loc: loc.latitude if loc else None)
dead_processed['longitude'] = dead_processed['location'].apply(lambda loc: loc.longitude if loc else None)

# drop location column
dead_processed_final = dead_processed.drop(columns=['location'])

# save
dead_processed_final.to_csv('SARS_dead.csv',index=False)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:31: DeprecationWarning: `country_bias` argument of the Nominatim.__init__ is deprecated and will be removed in geopy 2.0. Use Nominatim.geocode(country_codes='China') instead.

In [113]:
dead_processed

DateTime,2003-03-31,2003-04-02,2003-04-06,2003-04-09,2003-04-15 12:00,2003-04-18,2003-04-21,2003-04-22 20:00,2003-04-23 20:00,2003-04-24 20:00,...,2003-07-30 10:00,2003-08-02 10:00,2003-08-13 10:00,2003-08-14 10:00,2003-08-15 10:00,2003-08-16 10:00,province,location,latitude,longitude
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Anhui,"(安徽省, China 中国, (32.0, 117.0))",32.000000,117.000000
1,3.0,3.0,4.0,4.0,4.0,4.0,25.0,35.0,39.0,42.0,...,193.0,193.0,193.0,193.0,193.0,193.0,Beijing,"(北京市, 东城区, 北京市, 100010, China 中国, (39.906217, ...",39.906217,116.391276
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Chongqing,"(重庆市, 渝中区 (Yuzhong), 重庆市中心, 重庆市, 400014, China...",29.558571,106.549282
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Fujian,"(福建省, China 中国, (26.5450001, 117.842778))",26.545000,117.842778
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Gansu,"(甘肃省, China 中国, (38.0000001, 101.9999999))",38.000000,102.000000
5,40.0,40.0,43.0,44.0,45.0,45.0,48.0,49.0,49.0,50.0,...,57.0,57.0,57.0,57.0,57.0,57.0,Guangdong,"(广东省, China 中国, (23.1357694, 113.1982688))",23.135769,113.198269
6,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,Guangxi,"(广西壮族自治区, China 中国, (24.0, 109.0))",24.000000,109.000000
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Guizhou,"(贵州省, China 中国, (27.0, 107.0))",27.000000,107.000000
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.0,12.0,12.0,12.0,12.0,12.0,Hebei,"(河北省, China 中国, (39.0000001, 116.0))",39.000000,116.000000
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Heilongjiang,"(黑龙江省, China 中国, (48.0000047, 127.999992))",48.000005,127.999992
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Henan,"(河南省, China 中国, (34.0000001, 113.9999999))",34.000000,114.000000
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Hubei,"(湖北省, China 中国, (31.15172525, 112.878322246560...",31.151725,112.878322
12,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Hunan,"(湖南省, China 中国, (27.9995878, 112.009538))",27.999588,112.009538
13,3.0,3.0,3.0,3.0,3.0,3.0,6.0,6.0,6.0,6.0,...,28.0,28.0,28.0,28.0,28.0,28.0,Inner Mongolia,"(内蒙古自治区, China 中国, (43.2443242, 114.3251664))",43.244324,114.325166
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Jiangsu,"(江苏省, China 中国, (33.0000001, 119.9999999))",33.000000,120.000000
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Jiangxi,"(江西省, China 中国, (28.0, 116.0))",28.000000,116.000000
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,6.0,6.0,6.0,6.0,6.0,Jilin,"(吉林省, China 中国, (42.9995032, 125.9816054))",42.999503,125.981605
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,Liaoning,"(辽宁省, China 中国, (40.9975197, 122.9955469))",40.997520,122.995547
18,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,Ningxia,"(宁夏回族自治区, China 中国, (37.0000001, 105.9999999))",37.000000,106.000000
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Shaanxi,"(陕西省, China 中国, (36.0, 109.0))",36.000000,109.000000
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Shandong,"(山东省, China 中国, (36.0000001, 118.9999999))",36.000000,119.000000
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,2.0,2.0,2.0,2.0,Shanghai,"(上海市, 黄浦区, 上海市, 200010, China 中国, (31.2252985,...",31.225299,121.489050
22,0.0,0.0,1.0,2.0,7.0,7.0,7.0,7.0,7.0,8.0,...,24.0,24.0,24.0,24.0,24.0,24.0,Shanxi,"(山西省, China 中国, (37.0, 112.0))",37.000000,112.000000
23,0.0,0.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,Sichuan,"(四川省, China 中国, (30.5000001, 102.4999999))",30.500000,102.500000
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,...,14.0,14.0,14.0,14.0,14.0,14.0,Tianjin,"(天津市, 和平区 (Heping), 天津市, 300010, China 中国, (39...",39.123564,117.198078
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Xinjiang,"(新疆维吾尔自治区, China 中国, (41.7574769, 87.167384230...",41.757477,87.167384
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,Zhejiang,"(浙江省, China 中国, (29.0000001, 119.9999999))",29.000000,120.000000
27,46.0,49.0,53.0,55.0,64.0,79.0,92.0,106.0,110.0,115.0,...,349.0,349.0,349.0,349.0,349.0,349.0,all,"(Shqipëria, (41.000028, 19.9999619))",41.000028,19.999962